// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Txt2Sql2;

namespace Txt2Sql2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200117233342_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Txt2Sql2.GerberPasDaily", b =>
                {
                    b.Property<int>("PAS_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ACCTG_BASIS_CD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BCTR_CD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CLNDR_ACCTG_MNTH_NO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CLNDR_ACCTG_YR_NO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CLNDR_DT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CMPNY_CD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONVERTED_AMT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DBT_CR_IND")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EAS_ACCT_NO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HDR_DESC_TXT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LOB_CD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MEMO_CD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PLAN_CD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PLCY_NO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PRFT_CTR_TXT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REF_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REINS_CMPNY_CD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SAP_ACCT_NO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SRC_CD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STATE_CD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TAX_STAT_TXT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TRANS_DT")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PAS_ID");

                    b.ToTable("GERBER_PAS_DAILY");
                });
#pragma warning restore 612, 618
        }
    }
}
